// Generated by https?://quicktype.io

export interface PlanEstudiosI {
  uid?:     string;
  title?: string;
  description?: string;
  carrera?: string;
  dateExamen?: string;
  dateCreated?: string;
}
