// Generated by https://quicktype.io

export interface ProfileI {
  name:     string;
  lastname: string;
  dni:      string;
  phone:    string;
  email:    string;
  country:  string;
  city:     string;
  addres:   string;
  avatar:   string;
}
