// Generated by https?://quicktype.io

export interface SectionI {
  uid?:     string;
  section?: string;
  categoria?:      string;
  capacidad?:    string;
  carrera?:    string;
  teacher?:  string;
  note?: string;
  dateCreated?: string;
}
