// Generated by https?://quicktype.io

export interface TareasI {
  uid?:     string;
  title?: string;
  description?:      string;
  deadline?:    string;
  carrera?:    string;
  section?:  string;
  asignatura?:  string;
  url?: string;
  file?: string;
  dateCreated?: string;
}
